// Ensure the global staticContohIsiData object exists, or create it if it doesn't.
// This allows multiple thematic files to safely add their data.
if (typeof staticContohIsiData === 'undefined') {
    var staticContohIsiData = {};
}

// Add new data for "Pembangunan Diri & Kekeluargaan" (Items 56-65)
// Use Object.assign to merge the new data
// into the global staticContohIsiData object.
Object.assign(staticContohIsiData, {
    "Kekurangan Kemahiran Hidup: Kurang pendedahan kepada kemahiran praktikal seperti pengurusan masa atau penyelesaian masalah.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam berdaya dan salam kompeten. Selamat datang ke forum yang akan membincangkan asas-asas penting untuk kejayaan dalam kehidupan, iaitu kemahiran hidup.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Kekurangan Kemahiran Hidup' dalam kalangan pelajar. Ini merujuk kepada kurangnya pendedahan atau penguasaan kemahiran praktikal yang penting seperti pengurusan masa, penyelesaian masalah, membuat keputusan, komunikasi efektif, dan pengurusan stres.\n\nLATAR BELAKANG ISU: Sistem pendidikan kadangkala terlalu tertumpu kepada pencapaian akademik sehingga mengabaikan pembangunan kemahiran hidup yang penting untuk pelajar berfungsi dengan baik dalam kehidupan seharian dan alam dewasa. Kekurangan contoh atau latihan di rumah juga menjadi faktor.\n\nKEPENTINGAN ISU: Kemahiran hidup adalah penting untuk membantu pelajar menghadapi cabaran, membuat pilihan yang bijak, berdikari, dan menyesuaikan diri dengan pelbagai situasi. Tanpanya, mereka mungkin menghadapi kesukaran dalam mengurus diri, perhubungan, dan tanggungjawab.\n\nSOALAN FOKUS: Persoalan yang ingin saya ajukan: Bagaimanakah kemahiran hidup boleh diintegrasikan dengan lebih berkesan dalam sistem pendidikan formal dan tidak formal? Apakah peranan keluarga dan komuniti dalam memupuk kemahiran ini?",
            perkataan_sukar: [
                { perkataan: "Kompeten", maksud: "Cekap; mempunyai kebolehan atau kelayakan yang diperlukan." },
                { perkataan: "Praktikal", maksud: "Berkaitan dengan amalan atau penggunaan sebenar, bukan teori semata-mata." },
                { perkataan: "Efektif", maksud: "Berkesan; mendatangkan hasil yang diingini." },
                { perkataan: "Berdikari", maksud: "Boleh berdiri sendiri; tidak bergantung kepada orang lain." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Pengerusi. Kemahiran hidup adalah 'peralatan' asas yang perlu dimiliki oleh setiap individu untuk mengemudi lautan kehidupan yang penuh cabaran.\n\nPENDAPAT: Saya berpendapat bahawa pembangunan kemahiran hidup perlu menjadi agenda utama dalam pendidikan holistik pelajar. Ia bukan sekadar 'nice-to-have', tetapi satu keperluan asas untuk melahirkan individu yang seimbang dan berdaya tahan.\n\nALASAN: Ini kerana dunia hari ini semakin kompleks. Kejayaan bukan hanya diukur oleh sijil akademik, tetapi juga oleh keupayaan untuk berfikir secara kritis, berkomunikasi dengan baik, bekerja dalam pasukan, mengurus kewangan, dan menangani stres. Kemahiran ini membantu pelajar menyesuaikan diri dan berkembang maju.\n\nTANGGAPAN: Ada yang mungkin menganggap kemahiran hidup akan dipelajari secara semula jadi apabila pelajar dewasa. Namun, banyak kemahiran ini perlu diajar dan dilatih secara sengaja dan berstruktur untuk memastikan penguasaan yang baik.\n\nRUJUKAN: Pertubuhan Kesihatan Sedunia (WHO) telah mengenal pasti beberapa kemahiran hidup teras yang penting untuk kesejahteraan psikososial, termasuk pemikiran kritis, membuat keputusan, komunikasi interpersonal, dan pengurusan emosi. Banyak modul latihan telah dibangunkan berdasarkan ini.\n\nIMPLIKASI: Kekurangan kemahiran hidup boleh menyebabkan pelajar menghadapi kesukaran dalam melanjutkan pelajaran, mendapatkan pekerjaan, mengurus perhubungan, atau membuat keputusan penting dalam hidup. Mereka mungkin lebih mudah terdedah kepada tekanan atau pengaruh negatif.\n\nKESIMPULAN: Kesimpulannya, kemahiran hidup perlu diajar secara eksplisit dan diintegrasikan dalam pelbagai mata pelajaran serta aktiviti kokurikulum. Bengkel, simulasi, projek berasaskan komuniti, dan program mentor-mentee adalah antara kaedah yang boleh digunakan. Peranan ibu bapa dalam memberi peluang kepada anak-anak untuk mempraktikkan kemahiran ini di rumah juga amat penting.",
            perkataan_sukar: [
                { perkataan: "Mengemudi", maksud: "Mengarahkan atau memandu (sesuatu yang kompleks)." },
                { perkataan: "Holistik", maksud: "Menyeluruh; mempertimbangkan semua aspek." },
                { perkataan: "Berdaya tahan", maksud: "Mampu menghadapi atau pulih daripada kesukaran." },
                { perkataan: "Eksplisit", maksud: "Dinyatakan dengan jelas dan terang." }
            ]
        }
    },
    "Ketidakpastian Mengenai Masa Depan: Kebimbangan mengenai pekerjaan, kestabilan kewangan, dan kehidupan dewasa.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam harapan dan salam persediaan. Selamat datang ke forum yang akan membincangkan satu perasaan yang sering menghantui remaja, iaitu ketidakpastian mengenai masa depan.\n\nPENGENALAN ISU: Isu yang menjadi tumpuan kita ialah 'Ketidakpastian Mengenai Masa Depan'. Ini merujuk kepada kebimbangan dan kerisauan yang dialami oleh pelajar mengenai laluan kerjaya mereka selepas tamat sekolah, prospek pekerjaan, kestabilan kewangan, dan cabaran-cabaran kehidupan dewasa secara amnya.\n\nLATAR BELAKANG ISU: Dunia yang pesat berubah, pasaran kerja yang kompetitif, kos sara hidup yang meningkat, dan pendedahan kepada pelbagai pilihan (dan juga masalah global) boleh menyebabkan remaja merasa tidak pasti dan bimbang tentang apa yang menanti mereka.\n\nKEPENTINGAN ISU: Ketidakpastian yang berlebihan boleh menjejaskan motivasi pelajar, menyebabkan stres, anxieti, dan kesukaran untuk membuat perancangan. Ia juga boleh mempengaruhi pilihan pendidikan mereka dan kesejahteraan mental secara keseluruhan.\n\nSOALAN FOKUS: Persoalan untuk kita renungkan: Bagaimanakah kita boleh membantu pelajar mengurus perasaan tidak pasti ini dengan lebih baik dan membina keyakinan untuk menghadapi masa depan? Apakah peranan bimbingan kerjaya dan pendedahan awal kepada dunia pekerjaan?",
            perkataan_sukar: [
                { perkataan: "Menghantui", maksud: "Sentiasa mengganggu fikiran atau perasaan." },
                { perkataan: "Prospek", maksud: "Harapan atau kemungkinan untuk berjaya pada masa depan." },
                { perkataan: "Kompetitif", maksud: "Bersifat persaingan; memerlukan usaha kuat untuk berjaya." },
                { perkataan: "Anxieti", maksud: "Perasaan risau, gelisah, atau takut yang berlebihan." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Saudara Pengerusi. Ketidakpastian mengenai masa depan adalah satu pengalaman yang lumrah, terutamanya pada fasa transisi dari alam remaja ke dewasa.\n\nPENDAPAT: Saya berpendapat bahawa untuk menangani ketidakpastian ini, pelajar perlu dilengkapi dengan kemahiran merancang masa depan, keupayaan untuk menyesuaikan diri (adaptability), daya tahan (resilience), serta akses kepada maklumat dan bimbingan yang relevan.\n\nALASAN: Ini kerana masa depan tidak selalunya boleh diramal dengan tepat. Mempunyai kemahiran untuk meneroka pilihan, menetapkan matlamat yang fleksibel, dan belajar daripada kesilapan adalah lebih penting daripada mempunyai satu rancangan yang kaku. Sokongan emosi juga penting untuk membina keyakinan.\n\nTANGGAPAN: Ada yang mungkin menganggap kebimbangan ini sebagai sesuatu yang akan hilang dengan sendirinya apabila pelajar dewasa. Namun, tanpa panduan dan kemahiran yang betul, ketidakpastian ini boleh berlarutan dan menjejaskan potensi mereka.\n\nRUJUKAN: Program bimbingan kerjaya yang komprehensif, pendedahan kepada pelbagai industri melalui lawatan atau latihan industri, serta sesi kaunseling individu boleh membantu pelajar meneroka minat mereka, memahami pasaran kerja, dan membuat perancangan awal.\n\nIMPLIKASI: Ketidakpastian yang tidak terurus boleh membawa kepada pilihan kerjaya yang salah, penyesalan, kurangnya kepuasan kerja, atau kesukaran untuk mencapai kestabilan kewangan. Ia juga boleh menyumbang kepada stres dan masalah kesihatan mental.\n\nKESIMPULAN: Kesimpulannya, adalah penting untuk membantu pelajar melihat masa depan sebagai satu peluang, bukan ancaman. Ini melibatkan pembinaan keyakinan diri, pendedahan kepada pelbagai laluan kejayaan, dan pengajaran bahawa kegagalan adalah sebahagian daripada proses pembelajaran. Sokongan daripada keluarga dan mentor juga amat berharga.",
            perkataan_sukar: [
                { perkataan: "Lumrah", maksud: "Biasa atau semula jadi." },
                { perkataan: "Adaptability (Keupayaan untuk menyesuaikan diri)", maksud: "Kebolehan untuk berubah atau disesuaikan mengikut keadaan baru." },
                { perkataan: "Resilience (Daya tahan)", maksud: "Keupayaan untuk pulih dengan cepat daripada kesukaran." },
                { perkataan: "Kaku", maksud: "Tidak fleksibel atau sukar diubah." }
            ]
        }
    },
    "Kurang Peluang Pembangunan Bakat: Tiada platform untuk mengembangkan minat dan bakat.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam potensi dan salam kreativiti. Selamat datang ke forum yang akan membincangkan tentang peri pentingnya mengasah dan mengembangkan bakat pelajar.\n\nPENGENALAN ISU: Isu yang menjadi tumpuan kita ialah 'Kurang Peluang Pembangunan Bakat'. Ini merujuk kepada situasi di mana pelajar mungkin mempunyai minat atau bakat tertentu (sama ada dalam bidang akademik, sukan, seni, atau kemahiran lain), tetapi kekurangan platform, sumber, atau galakan untuk mengembangkannya.\n\nLATAR BELAKANG ISU: Sistem pendidikan yang terlalu berfokus pada peperiksaan, kekurangan kemudahan atau jurulatih/pembimbing yang berkelayakan, kekangan kewangan, atau kurangnya kesedaran tentang kepentingan pembangunan bakat di luar bidang akademik boleh menyumbang kepada masalah ini.\n\nKEPENTINGAN ISU: Setiap pelajar mempunyai potensi dan bakat yang unik. Pembangunan bakat bukan sahaja penting untuk kepuasan diri dan pembentukan identiti, tetapi juga boleh membuka laluan kerjaya dan menyumbang kepada kepelbagaian modal insan negara.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah kita boleh mewujudkan lebih banyak peluang dan platform untuk pelajar mengenali, meneroka, dan mengembangkan bakat mereka? Apakah peranan sekolah, keluarga, dan komuniti dalam menyokong usaha ini?",
            perkataan_sukar: [
                { perkataan: "Mengasah", maksud: "Menajamkan atau meningkatkan (kemahiran, bakat)." },
                { perkataan: "Platform", maksud: "Wadah atau medium untuk melakukan sesuatu." },
                { perkataan: "Galakan", maksud: "Dorongan atau sokongan." },
                { perkataan: "Modal insan", maksud: "Sumber manusia yang berkualiti dari segi pengetahuan, kemahiran, dan sahsiah." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Moderator. Mengabaikan pembangunan bakat pelajar adalah seperti membiarkan permata terbiar tanpa digilap – satu kerugian besar.\n\nPENDAPAT: Saya berpendapat bahawa sistem pendidikan dan masyarakat perlu memberi pengiktirafan yang lebih tinggi kepada pelbagai jenis bakat, bukan hanya kecemerlangan akademik. Perlu ada pelaburan yang lebih besar dalam menyediakan sumber dan peluang untuk pembangunan bakat secara menyeluruh.\n\nALASAN: Ini kerana bakat yang dipupuk boleh meningkatkan keyakinan diri, motivasi, dan kreativiti pelajar. Ia juga memberi mereka alternatif laluan kejayaan dan mengurangkan tekanan untuk cemerlang dalam satu acuan sahaja. Kepelbagaian bakat memperkaya masyarakat.\n\nTANGGAPAN: Ada yang mungkin menganggap pembangunan bakat (terutamanya dalam bidang bukan akademik) sebagai aktiviti sampingan atau hobi semata-mata. Namun, banyak industri kreatif dan sukan kini menawarkan peluang kerjaya yang cerah, dan ia bermula daripada pemupukan bakat dari awal.\n\nRUJUKAN: Konsep 'Multiple Intelligences' oleh Howard Gardner menekankan bahawa terdapat pelbagai jenis kecerdasan atau bakat (seperti muzik, kinestetik, interpersonal) yang perlu dikenal pasti dan dibangunkan. Sekolah boleh menggunakan pendekatan ini untuk mempelbagaikan aktiviti.\n\nIMPLIKASI: Kekurangan peluang pembangunan bakat boleh menyebabkan potensi pelajar terpendam, rasa tidak puas hati, dan kehilangan sumbangan berharga kepada masyarakat. Pelajar juga mungkin merasa kurang dihargai jika bakat mereka tidak diiktiraf.\n\nKESIMPULAN: Kesimpulannya, adalah penting untuk mewujudkan ekosistem yang menyokong pembangunan bakat. Ini termasuk mempelbagaikan aktiviti kokurikulum, menyediakan kemudahan dan jurulatih, mengadakan pertandingan atau pameran bakat, serta memberi pendedahan kepada profesional dalam pelbagai bidang. Sokongan ibu bapa dalam menggalakkan minat anak-anak juga amat kritikal.",
            perkataan_sukar: [
                { perkataan: "Digilap", maksud: "Diasah atau diperbaiki sehingga menjadi baik atau cemerlang." },
                { perkataan: "Acuan", maksud: "Bentuk atau model tertentu." },
                { perkataan: "Sampingan", maksud: "Bukan yang utama atau tambahan sahaja." },
                { perkataan: "Kinestetik", maksud: "Berkaitan dengan pergerakan fizikal dan koordinasi." }
            ]
        }
    },
    "Masalah Keluarga: Konflik ibu bapa, perceraian, atau isu kewangan keluarga yang memberi kesan kepada pelajar.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam harmoni dan salam keprihatinan. Selamat datang ke forum yang akan membincangkan pengaruh institusi keluarga terhadap kesejahteraan pelajar.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Masalah Keluarga'. Ini merujuk kepada situasi seperti konflik yang berterusan antara ibu bapa, proses perceraian, masalah kewangan keluarga yang meruncing, penderaan, atau pengabaian, yang semuanya boleh memberi kesan mendalam kepada emosi dan tumpuan pelajar.\n\nLATAR BELAKANG ISU: Keluarga adalah unit asas masyarakat dan sepatutnya menjadi sumber sokongan utama. Namun, pelbagai tekanan hidup boleh menyebabkan masalah dalam keluarga, dan pelajar seringkali menjadi mangsa keadaan, terperangkap di tengah-tengah konflik atau kesusahan.\n\nKEPENTINGAN ISU: Masalah keluarga boleh menjejaskan kesihatan mental pelajar (menyebabkan stres, kemurungan, anxieti), tingkah laku mereka di sekolah (menjadi agresif atau menarik diri), prestasi akademik, dan pandangan mereka terhadap perhubungan dan institusi keluarga pada masa hadapan.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah pihak sekolah dan kaunselor dapat mengenal pasti dan memberi sokongan kepada pelajar yang menghadapi masalah keluarga? Apakah peranan komuniti dalam membantu keluarga yang berdepan dengan krisis?",
            perkataan_sukar: [
                { perkataan: "Institusi keluarga", maksud: "Unit asas dalam masyarakat yang terdiri daripada ibu bapa dan anak-anak." },
                { perkataan: "Meruncing", maksud: "Menjadi semakin serius atau kritikal." },
                { perkataan: "Pengabaian", maksud: "Kegagalan untuk memberi perhatian atau penjagaan yang sewajarnya." },
                { perkataan: "Mangsa keadaan", maksud: "Seseorang yang menderita akibat situasi yang bukan salahnya." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Moderator. Kestabilan dan keharmonian keluarga adalah asas kepada perkembangan sihat seorang kanak-kanak dan remaja.\n\nPENDAPAT: Saya berpendapat bahawa pelajar yang datang dari latar belakang keluarga yang bermasalah memerlukan sokongan emosi dan psikologi yang khusus dan penuh empati. Sekolah perlu menjadi 'tempat selamat' bagi mereka.\n\nALASAN: Ini kerana pelajar ini mungkin membawa beban emosi yang berat ke sekolah, yang mengganggu keupayaan mereka untuk belajar dan bersosial. Mereka mungkin merasa malu, marah, sedih, atau keliru. Sokongan yang betul boleh membantu mereka mengurus perasaan ini dan mengurangkan kesan negatif.\n\nTANGGAPAN: Ada yang mungkin menganggap masalah keluarga adalah urusan peribadi dan sekolah tidak patut campur tangan. Namun, jika ia memberi kesan kepada kesejahteraan dan pembelajaran pelajar, pihak sekolah mempunyai tanggungjawab untuk memberi sokongan yang bersesuaian, dengan menghormati privasi keluarga.\n\nRUJUKAN: Khidmat kaunseling sekolah, pekerja sosial, dan agensi komuniti yang memberi fokus kepada sokongan keluarga (seperti Jabatan Kebajikan Masyarakat atau NGO) boleh memainkan peranan penting dalam memberi bantuan kepada pelajar dan keluarga yang memerlukan.\n\nIMPLIKASI: Masalah keluarga yang tidak ditangani boleh membawa kepada masalah tingkah laku pelajar, keciciran sekolah, penglibatan dalam aktiviti negatif sebagai cara melarikan diri, dan kitaran masalah keluarga yang berulang pada generasi akan datang.\n\nKESIMPULAN: Kesimpulannya, adalah penting untuk mewujudkan jaringan sokongan bagi pelajar yang menghadapi masalah keluarga. Guru perlu peka terhadap perubahan tingkah laku pelajar. Kaunselor perlu mudah diakses. Kerjasama dengan ibu bapa (jika sesuai) dan agensi luar juga perlu diperkukuh untuk menyediakan bantuan yang komprehensif.",
            perkataan_sukar: [
                { perkataan: "Empati", maksud: "Kebolehan untuk memahami dan berkongsi perasaan orang lain." },
                { perkataan: "Psikologi", maksud: "Berkaitan dengan minda atau perasaan." },
                { perkataan: "Privasi", maksud: "Kerahsiaan atau hak untuk bersendirian." },
                { perkataan: "Komprehensif", maksud: "Menyeluruh dan lengkap." }
            ]
        }
    },
    "Kurang Sokongan Keluarga: Rasa tidak difahami atau disokong oleh ahli keluarga.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam kasih sayang dan salam pengertian. Selamat datang ke forum yang akan menyentuh tentang kepentingan sokongan keluarga dalam kehidupan pelajar.\n\nPENGENALAN ISU: Isu yang menjadi tumpuan kita ialah 'Kurang Sokongan Keluarga'. Ini merujuk kepada situasi di mana pelajar merasa tidak difahami, tidak didengari, diabaikan, atau tidak mendapat sokongan emosi, galakan, atau bantuan yang diperlukan daripada ahli keluarga, terutamanya ibu bapa.\n\nLATAR BELAKANG ISU: Kurangnya sokongan ini boleh berpunca daripada pelbagai faktor, seperti ibu bapa yang terlalu sibuk bekerja, kurangnya kemahiran keibubapaan, masalah komunikasi dalam keluarga, harapan yang tidak realistik, atau ketidaksefahaman antara generasi.\n\nKEPENTINGAN ISU: Sokongan keluarga adalah amat penting untuk pembentukan keyakinan diri, kesejahteraan emosi, dan motivasi pelajar. Pelajar yang merasa disokong lebih cenderung untuk berjaya dalam pelajaran, mempunyai harga diri yang tinggi, dan lebih berdaya tahan menghadapi cabaran.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Apakah tanda-tanda pelajar yang kurang mendapat sokongan keluarga? Bagaimanakah kita boleh membantu merapatkan jurang komunikasi dan persefahaman antara pelajar dan ahli keluarga mereka?",
            perkataan_sukar: [
                { perkataan: "Galakan", maksud: "Dorongan atau sokongan." },
                { perkataan: "Kemahiran keibubapaan", maksud: "Kebolehan dan pengetahuan untuk menjadi ibu bapa yang baik." },
                { perkataan: "Ketidaksefahaman", maksud: "Ketiadaan persefahaman atau salah faham." },
                { perkataan: "Berdaya tahan", maksud: "Mampu menghadapi atau pulih daripada kesukaran." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Saudari Pengerusi. Keluarga adalah sauh dalam kehidupan seseorang. Tanpa sokongan keluarga, remaja boleh merasa terumbang-ambing.\n\nPENDAPAT: Saya berpendapat bahawa usaha untuk meningkatkan sokongan keluarga memerlukan pendidikan keibubapaan yang berterusan, pengukuhan kemahiran komunikasi dalam keluarga, dan kesedaran tentang peranan penting sokongan emosi dalam perkembangan remaja.\n\nALASAN: Ini kerana ramai ibu bapa mungkin sayang kepada anak-anak mereka tetapi tidak tahu cara terbaik untuk menunjukkan sokongan atau berkomunikasi secara efektif. Pelajar pula mungkin tidak tahu cara untuk meluahkan keperluan mereka. Salah faham mudah berlaku.\n\nTANGGAPAN: Ada yang mungkin menganggap pelajar perlu berdikari dan tidak terlalu bergantung kepada sokongan keluarga. Walaupun kemandirian itu penting, sokongan keluarga memberi asas yang kukuh untuk pelajar meneroka dunia dengan lebih yakin.\n\nRUJUKAN: Program-program seperti kursus keibubapaan, terapi keluarga, atau sesi dialog antara ibu bapa dan anak boleh membantu meningkatkan kualiti hubungan dan sokongan dalam keluarga. Sekolah melalui PIBG juga boleh memainkan peranan.\n\nIMPLIKASI: Kurang sokongan keluarga boleh menyebabkan pelajar merasa sunyi, rendah diri, tidak bermotivasi, lebih mudah terpengaruh dengan perkara negatif, dan menghadapi masalah dalam perhubungan interpersonal. Ia juga boleh menyumbang kepada masalah kesihatan mental.\n\nKESIMPULAN: Kesimpulannya, membina keluarga yang menyokong adalah tanggungjawab bersama. Ibu bapa perlu meluangkan masa berkualiti dengan anak-anak, mendengar secara aktif, dan memberi galakan. Sekolah boleh menyediakan platform untuk penglibatan ibu bapa dan memberi sumber jika ada keluarga yang memerlukan bantuan.",
            perkataan_sukar: [
                { perkataan: "Sauh", maksud: "(Kiasan) Sesuatu yang memberi kestabilan atau pegangan." },
                { perkataan: "Terumbang-ambing", maksud: "Tidak tetap atau tidak menentu." },
                { perkataan: "Efektif", maksud: "Berkesan atau mendatangkan hasil." },
                { perkataan: "Interpersonal", maksud: "Antara individu dengan individu lain." }
            ]
        }
    },
    "Jangkaan Ibu Bapa yang Terlalu Tinggi: Tekanan daripada ibu bapa untuk mencapai keputusan cemerlang.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam realistik dan salam kasih sayang. Selamat datang ke forum yang akan membincangkan tentang harapan dan tekanan dalam hubungan kekeluargaan.\n\nPENGENALAN ISU: Isu yang akan kita kupas ialah 'Jangkaan Ibu Bapa yang Terlalu Tinggi'. Ini merujuk kepada situasi di mana ibu bapa meletakkan harapan atau tekanan yang sangat tinggi, selalunya berkaitan pencapaian akademik, kepada anak-anak mereka, kadangkala sehingga melebihi kemampuan atau minat sebenar anak itu.\n\nLATAR BELAKANG ISU: Jangkaan ini mungkin berpunca daripada keinginan ibu bapa untuk melihat anak berjaya, pengalaman peribadi mereka, perbandingan dengan anak orang lain, atau tekanan daripada masyarakat. Niatnya mungkin baik, tetapi caranya boleh memberi kesan negatif.\n\nKEPENTINGAN ISU: Jangkaan yang terlalu tinggi dan tidak realistik boleh menyebabkan pelajar mengalami stres yang melampau, ketakutan akan kegagalan, kehilangan minat belajar (jika dipaksa), perasaan tidak cukup baik, malah kemurungan atau pemberontakan.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah ibu bapa boleh menetapkan jangkaan yang sihat dan menyokong, yang menggalakkan kecemerlangan tanpa membebankan anak-anak? Apakah peranan komunikasi dalam mengurus jangkaan ini?",
            perkataan_sukar: [
                { perkataan: "Realistik", maksud: "Berdasarkan kenyataan atau keadaan sebenar." },
                { perkataan: "Kemampuan", maksud: "Kebolehan atau keupayaan." },
                { perkataan: "Melampau", maksud: "Berlebihan atau melampaui batas." },
                { perkataan: "Pemberontakan", maksud: "Tindakan menentang atau tidak mahu patuh." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Moderator. Setiap ibu bapa mahukan yang terbaik untuk anak mereka, tetapi 'terbaik' itu perlu didefinisikan secara sihat dan realistik.\n\nPENDAPAT: Saya berpendapat bahawa ibu bapa perlu belajar untuk memahami potensi dan minat unik setiap anak, serta meraikan usaha dan kemajuan, bukan hanya keputusan akhir. Komunikasi terbuka mengenai harapan dan kebimbangan adalah kunci.\n\nALASAN: Ini kerana setiap anak adalah berbeza. Memaksa mereka mengikut acuan tertentu atau membandingkan mereka dengan orang lain boleh membunuh motivasi dan keyakinan diri. Jangkaan yang sihat adalah yang selari dengan kebolehan anak dan memberi ruang untuk mereka berkembang mengikut rentak sendiri.\n\nTANGGAPAN: Ada ibu bapa yang mungkin berfikir bahawa tekanan itu perlu untuk mendorong anak berusaha lebih kuat. Walaupun sedikit cabaran itu baik, tekanan yang berlebihan boleh menjadi toksik dan membawa kesan sebaliknya, iaitu pelajar 'burnout' atau hilang minat.\n\nRUJUKAN: Pakar psikologi perkembangan kanak-kanak menekankan kepentingan pendekatan 'authoritative parenting' (keibubapaan berwibawa), di mana ibu bapa mempunyai jangkaan yang jelas tetapi juga bersifat responsif, menyokong, dan memberi autonomi kepada anak-anak.\n\nIMPLIKASI: Jangkaan yang terlalu tinggi boleh merosakkan hubungan antara ibu bapa dan anak, menyebabkan anak merasa tidak pernah cukup baik, meningkatkan risiko masalah kesihatan mental, dan mungkin mendorong anak untuk menipu demi memenuhi harapan.\n\nKESIMPULAN: Kesimpulannya, adalah penting bagi ibu bapa untuk mengimbangi antara harapan dan sokongan. Fokus kepada proses pembelajaran dan pembangunan sahsiah anak, bukan hanya gred. Raikan setiap pencapaian, walau sekecil mana pun. Paling penting, pastikan anak tahu bahawa kasih sayang ibu bapa tidak bersyarat pada pencapaian mereka.",
            perkataan_sukar: [
                { perkataan: "Acuan", maksud: "Bentuk atau model tertentu." },
                { perkataan: "Rentak", maksud: "Kadar kelajuan atau irama." },
                { perkataan: "Toksik", maksud: "Beracun atau memudaratkan." },
                { perkataan: "Autonomi", maksud: "Kebebasan untuk membuat keputusan sendiri." }
            ]
        }
    },
    "Kurang Komunikasi dengan Ibu Bapa: Kesukaran untuk berbincang masalah dengan ibu bapa.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam mesra dan salam pendengar setia. Selamat datang ke forum yang akan membincangkan jambatan penting dalam keluarga, iaitu komunikasi.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Kurang Komunikasi dengan Ibu Bapa'. Ini merujuk kepada kesukaran yang dihadapi oleh pelajar untuk berbual, meluahkan perasaan, atau membincangkan masalah peribadi mereka dengan ibu bapa secara terbuka dan jujur.\n\nLATAR BELAKANG ISU: Jurang komunikasi ini boleh disebabkan oleh pelbagai faktor, seperti ibu bapa yang terlalu sibuk, jurang generasi dan perbezaan pandangan, ketakutan pelajar akan dihakimi atau dimarahi, kurangnya kemahiran mendengar dalam kalangan ibu bapa, atau tiada masa berkualiti yang diluangkan bersama.\n\nKEPENTINGAN ISU: Komunikasi yang baik dengan ibu bapa adalah penting untuk kesejahteraan emosi pelajar. Ia memberi mereka rasa selamat, difahami, dan mempunyai tempat untuk merujuk apabila menghadapi masalah. Kekurangan komunikasi boleh menyebabkan pelajar merasa terasing atau mencari penyelesaian daripada sumber yang salah.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Apakah halangan-halangan utama kepada komunikasi yang efektif antara pelajar dan ibu bapa? Bagaimanakah kedua-dua pihak boleh berusaha untuk membina jambatan komunikasi yang lebih kukuh?",
            perkataan_sukar: [
                { perkataan: "Meluahkan", maksud: "Menyatakan atau mengeluarkan (perasaan, pendapat)." },
                { perkataan: "Jurang generasi", maksud: "Perbezaan pandangan, nilai, atau cara hidup antara generasi tua dan muda." },
                { perkataan: "Dihakimi", maksud: "Dinilai atau dikritik (selalunya secara negatif)." },
                { perkataan: "Terasing", maksud: "Merasa tersisih atau jauh daripada orang lain." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Saudari Pengerusi. Komunikasi adalah nadi kepada perhubungan yang sihat, terutamanya dalam institusi keluarga.\n\nPENDAPAT: Saya berpendapat bahawa membina komunikasi yang efektif antara ibu bapa dan anak-anak memerlukan usaha sedar daripada kedua-dua pihak. Ibu bapa perlu belajar untuk menjadi pendengar yang baik dan mewujudkan suasana yang tidak menghakimi. Anak-anak pula perlu berani untuk berkongsi.\n\nALASAN: Ini kerana apabila pelajar merasa selamat dan selesa untuk berbincang dengan ibu bapa, mereka lebih cenderung untuk mendapatkan nasihat yang betul dan sokongan emosi apabila diperlukan. Ini boleh mencegah mereka daripada terjerumus ke dalam masalah yang lebih besar atau merasa bersendirian.\n\nTANGGAPAN: Ada ibu bapa yang mungkin merasa mereka sudah cukup berkomunikasi dengan bertanya tentang sekolah atau memberi arahan. Namun, komunikasi yang bermakna melibatkan perkongsian perasaan, pandangan, dan pendengaran yang aktif, bukan sekadar interaksi sehala.\n\nRUJUKAN: Teknik-teknik komunikasi seperti 'active listening' (pendengaran aktif), penggunaan 'I-statements' (kenyataan-saya) untuk meluahkan perasaan, dan penetapan masa khas untuk berbual (family time) boleh membantu meningkatkan kualiti komunikasi dalam keluarga.\n\nIMPLIKASI: Kurang komunikasi dengan ibu bapa boleh menyebabkan pelajar mencari perhatian atau sokongan daripada pihak luar yang mungkin tidak baik, memendam perasaan yang boleh membawa kepada stres atau kemurungan, dan merenggangkan hubungan kekeluargaan.\n\nKESIMPULAN: Kesimpulannya, usaha untuk memperbaiki komunikasi perlu berterusan. Ibu bapa boleh memulakan dengan meluangkan masa tanpa gangguan untuk berbual dengan anak-anak, menunjukkan minat yang tulus terhadap kehidupan mereka, dan memberi respons dengan sabar dan penuh pemahaman. Pelajar juga boleh cuba untuk lebih terbuka secara beransur-ansur.",
            perkataan_sukar: [
                { perkataan: "Sedar", maksud: "Menyedari atau insaf." },
                { perkataan: "Tidak menghakimi", maksud: "Tidak membuat penilaian atau kritikan negatif." },
                { perkataan: "Sehala", maksud: "Satu arah sahaja." },
                { perkataan: "Pendengaran aktif (Active listening)", maksud: "Mendengar dengan penuh tumpuan dan usaha untuk memahami." }
            ]
        }
    },
    "Kekurangan Wang Saku/Perbelanjaan: Kesukaran menampung perbelanjaan harian atau keperluan sekolah.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam prihatin dan salam sokongan. Selamat datang ke forum yang akan membincangkan satu cabaran praktikal yang dihadapi oleh sesetengah pelajar, iaitu isu kewangan.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Kekurangan Wang Saku atau Perbelanjaan'. Ini merujuk kepada situasi di mana pelajar menghadapi kesukaran untuk menampung perbelanjaan harian mereka, seperti tambang ke sekolah, makanan, atau keperluan asas persekolahan akibat kekangan kewangan keluarga.\n\nLATAR BELAKANG ISU: Isu ini seringkali berkait rapat dengan status sosioekonomi keluarga. Kehilangan pekerjaan ibu bapa, kos sara hidup yang tinggi, bilangan tanggungan yang ramai, atau pengurusan kewangan keluarga yang kurang baik boleh menyebabkan pelajar tidak mendapat wang saku yang mencukupi.\n\nKEPENTINGAN ISU: Kekurangan wang saku boleh memberi kesan kepada pelbagai aspek kehidupan pelajar. Ia boleh menyebabkan mereka berlapar, tidak dapat membeli bahan rujukan penting, merasa malu atau rendah diri berbanding rakan-rakan, malah dalam kes ekstrem, boleh mendorong mereka untuk mencari jalan mudah yang salah.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah pihak sekolah dan komuniti boleh membantu mengenal pasti dan menyalurkan bantuan kepada pelajar yang menghadapi masalah kewangan ini? Apakah skim bantuan yang sedia ada dan sejauh mana keberkesanannya?",
            perkataan_sukar: [
                { perkataan: "Menampung", maksud: "Mencukupi atau membiayai (perbelanjaan)." },
                { perkataan: "Kekangan", maksud: "Halangan atau batasan." },
                { perkataan: "Sosioekonomi", maksud: "Berkaitan dengan faktor sosial dan ekonomi." },
                { perkataan: "Skim", maksud: "Rancangan atau program." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Moderator. Isu kekurangan wang saku pelajar adalah satu realiti pahit yang memerlukan keprihatinan dan tindakan daripada kita semua sebagai sebuah masyarakat penyayang.\n\nPENDAPAT: Saya berpendapat bahawa tiada pelajar yang patut tercicir daripada pendidikan atau terpaksa menanggung kesusahan akibat masalah kewangan keluarga. Sistem sokongan yang komprehensif perlu diwujudkan untuk membantu mereka.\n\nALASAN: Ini kerana kesukaran kewangan boleh menjadi penghalang besar kepada pembelajaran. Pelajar yang lapar atau bimbang tentang perbelanjaan sukar untuk menumpukan perhatian di dalam kelas. Bantuan yang diberikan, walaupun kecil, boleh memberi perbezaan yang besar kepada kehidupan mereka.\n\nTANGGAPAN: Ada yang mungkin berfikir ini adalah tanggungjawab keluarga semata-mata. Walaupun keluarga memainkan peranan utama, masyarakat dan kerajaan juga mempunyai peranan dalam memastikan kebajikan asas setiap kanak-kanak, termasuk hak untuk mendapat pendidikan, terpelihara.\n\nRUJUKAN: Pelbagai skim bantuan kewangan seperti Kumpulan Wang Amanah Pelajar Miskin (KWAPM), Rancangan Makanan Tambahan (RMT), bantuan pakaian seragam, dan biasiswa daripada pelbagai agensi kerajaan dan swasta bertujuan untuk membantu pelajar daripada keluarga berpendapatan rendah.\n\nIMPLIKASI: Kekurangan wang saku yang kronik boleh menyebabkan pelajar merasa tertekan, malu untuk ke sekolah (jika tidak mampu membeli keperluan), ponteng sekolah untuk bekerja, atau terlibat dalam aktiviti tidak sihat untuk mendapatkan wang. Ia juga melebarkan jurang ketidaksamaan.\n\nKESIMPULAN: Kesimpulannya, adalah penting untuk memastikan semua pelajar yang layak mendapat bantuan kewangan. Pihak sekolah perlu proaktif dalam mengenal pasti pelajar yang memerlukan bantuan dan memudahkan proses permohonan. Masyarakat juga boleh menyumbang melalui tabung kebajikan sekolah atau NGO. Mendidik tentang pengurusan kewangan juga penting agar bantuan yang diterima digunakan dengan bijak.",
            perkataan_sukar: [
                { perkataan: "Tercicir", maksud: "Ketinggalan atau tidak dapat meneruskan (pelajaran)." },
                { perkataan: "Komprehensif", maksud: "Menyeluruh dan lengkap." },
                { perkataan: "Terpelihara", maksud: "Terjaga atau dilindungi." },
                { perkataan: "Proaktif", maksud: "Mengambil langkah awal untuk bertindak." }
            ]
        }
    },
    "Kurang Celik Kewangan: Kurang pengetahuan mengenai pengurusan wang dan simpanan.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam bijak wang dan salam masa depan terjamin. Selamat datang ke forum yang akan membincangkan satu kemahiran penting untuk kehidupan, iaitu celik kewangan.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Kurang Celik Kewangan' dalam kalangan pelajar. Ini merujuk kepada kekurangan pengetahuan, kemahiran, dan keyakinan untuk mengurus wang peribadi secara efektif, termasuk membuat bajet, menabung, berbelanja secara bijak, dan memahami konsep asas kewangan.\n\nLATAR BELAKANG ISU: Dalam dunia moden yang kompleks dengan pelbagai produk kewangan dan godaan perbelanjaan, ramai pelajar (dan juga orang dewasa) tidak mendapat pendidikan formal atau tidak formal yang mencukupi mengenai pengurusan kewangan. Mereka mungkin belajar melalui kesilapan atau tidak belajar langsung.\n\nKEPENTINGAN ISU: Celik kewangan adalah penting untuk membantu pelajar membuat keputusan kewangan yang baik sepanjang hayat mereka, mengelakkan hutang yang tidak perlu, merancang untuk masa depan (seperti pendidikan tinggi atau pembelian aset), dan mencapai kestabilan kewangan.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah pendidikan celik kewangan boleh diterapkan secara berkesan kepada pelajar dari peringkat awal? Apakah topik-topik utama yang perlu diberi penekanan?",
            perkataan_sukar: [
                { perkataan: "Celik kewangan", maksud: "Pengetahuan dan kemahiran untuk mengurus kewangan peribadi dengan baik." },
                { perkataan: "Bajet", maksud: "Anggaran perbelanjaan dan pendapatan." },
                { perkataan: "Aset", maksud: "Harta yang bernilai." },
                { perkataan: "Kestabilan kewangan", maksud: "Keadaan kewangan yang kukuh dan selamat." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Saudari Pengerusi. Celik kewangan adalah pasport kepada kebebasan dan keselamatan kewangan pada masa hadapan.\n\nPENDAPAT: Saya berpendapat bahawa pendidikan celik kewangan perlu diintegrasikan dalam kurikulum sekolah dan juga diperkukuh melalui program-program di luar sekolah. Ia perlu praktikal, relevan dengan kehidupan pelajar, dan disampaikan dengan cara yang menarik.\n\nALASAN: Ini kerana tabiat pengurusan wang yang baik perlu dipupuk sejak usia muda. Pelajar yang faham konsep seperti kepentingan menabung, perbezaan antara keperluan dan kehendak, serta bahaya hutang, lebih bersedia untuk mengurus kewangan mereka apabila dewasa dan mendapat pendapatan sendiri.\n\nTANGGAPAN: Ada yang mungkin menganggap topik kewangan terlalu rumit untuk pelajar atau ia tanggungjawab ibu bapa sepenuhnya. Namun, asas-asas kewangan boleh diajar dengan cara yang mudah difahami, dan sekolah boleh melengkapkan apa yang diajar di rumah (atau mengisi kekosongan jika tidak diajar di rumah).\n\nRUJUKAN: Banyak modul pendidikan kewangan untuk pelajar telah dibangunkan oleh institusi seperti Bank Negara Malaysia (melalui Agensi Kaunseling dan Pengurusan Kredit - AKPK) dan institusi kewangan lain. Ini merangkumi topik seperti simpanan, pelaburan asas, dan pengurusan hutang.\n\nIMPLIKASI: Kurang celik kewangan boleh menyebabkan individu terjerat dalam hutang, menjadi mangsa penipuan kewangan, gagal merancang untuk persaraan, dan mengalami stres kewangan yang berpanjangan, yang boleh menjejaskan aspek lain kehidupan.\n\nKESIMPULAN: Kesimpulannya, adalah penting untuk memperkasakan pelajar dengan ilmu celik kewangan. Ini boleh dilakukan melalui mata pelajaran seperti Matematik atau Ekonomi, kelab keusahawanan, ceramah, atau permainan simulasi kewangan. Menggalakkan tabiat menabung dari kecil dan memberi contoh pengurusan wang yang baik oleh orang dewasa juga amat membantu.",
            perkataan_sukar: [
                { perkataan: "Pasport", maksud: "(Kiasan) Sesuatu yang membolehkan akses atau kejayaan." },
                { perkataan: "Diintegrasikan", maksud: "Digabungkan atau disatukan." },
                { perkataan: "Kehendak", maksud: "Sesuatu yang diingini tetapi tidak semestinya diperlukan." },
                { perkataan: "Simulasi", maksud: "Peniruan keadaan sebenar untuk tujuan latihan atau kajian." }
            ]
        }
    },
    "Tekanan untuk Memiliki Barangan Berjenama: Rasa tertekan untuk memiliki barangan mewah seperti rakan-rakan.": {
        moderator: {
            hujah: "SALAM PEMBUKA: Salam sederhana dan salam bijak berbelanja. Selamat datang ke forum yang akan membincangkan tentang pengaruh budaya kebendaan dalam kalangan remaja.\n\nPENGENALAN ISU: Isu yang menjadi fokus kita ialah 'Tekanan untuk Memiliki Barangan Berjenama'. Ini merujuk kepada perasaan tertekan atau keinginan yang kuat dalam kalangan pelajar untuk memiliki barangan mewah, berjenama terkenal, atau gajet terkini semata-mata untuk diterima oleh rakan sebaya, kelihatan 'trendy', atau meningkatkan status sosial.\n\nLATAR BELAKANG ISU: Pengaruh media sosial yang sering memaparkan gaya hidup mewah, iklan yang agresif, dan budaya perbandingan dengan rakan sebaya menyumbang kepada tekanan ini. Pelajar mungkin merasa rendah diri atau tersisih jika tidak memiliki barangan tertentu.\n\nKEPENTINGAN ISU: Tekanan ini boleh membawa kepada tabiat berbelanja yang tidak sihat, meminta wang secara berlebihan daripada ibu bapa, rasa tidak puas hati yang berterusan, malah dalam kes ekstrem, terlibat dalam aktiviti tidak bermoral untuk mendapatkan wang. Ia juga mengalih fokus daripada nilai-nilai yang lebih penting.\n\nSOALAN FOKUS: Persoalan untuk kita bincangkan: Bagaimanakah kita boleh membantu pelajar untuk lebih menghargai nilai sebenar sesuatu barangan berbanding jenamanya, dan membina keyakinan diri yang tidak bersandarkan kepada pemilikan material? Apakah peranan pendidikan pengguna?",
            perkataan_sukar: [
                { perkataan: "Kebendaan", maksud: "Sifat terlalu mementingkan harta benda atau kemewahan material." },
                { perkataan: "Berjenama", maksud: "Mempunyai jenama atau cap dagang yang terkenal." },
                { perkataan: "'Trendy'", maksud: "(Ungkapan Inggeris) Mengikut perkembangan atau gaya terkini." },
                { perkataan: "Material", maksud: "Berkaitan dengan harta benda atau wang." }
            ]
        },
        panelis: {
            hujah: "PENDAHULUAN PANELIS: Terima kasih Tuan Pengerusi. Dalam dunia yang dipenuhi dengan pemasaran dan imej, tekanan untuk memiliki barangan berjenama adalah satu cabaran yang dihadapi oleh ramai, terutamanya golongan muda.\n\nPENDAPAT: Saya berpendapat bahawa adalah penting untuk mendidik pelajar tentang nilai wang, perbezaan antara keperluan dan kehendak, serta bahaya terikut-ikut dengan budaya kebendaan. Harga diri sejati datang dari dalam, bukan dari label pada pakaian atau gajet.\n\nALASAN: Ini kerana keinginan untuk memiliki barangan berjenama seringkali didorong oleh faktor luaran seperti penerimaan sosial, bukan keperluan sebenar. Ia boleh mewujudkan kitaran perbelanjaan yang tidak berkesudahan dan hutang. Lebih penting untuk melabur dalam pengalaman, ilmu, atau kemahiran.\n\nTANGGAPAN: Ada yang mungkin menganggap memiliki barangan berjenama itu hak individu atau lambang kejayaan. Walaupun tiada salahnya jika berkemampuan, masalah timbul apabila ia menjadi satu tekanan atau keutamaan yang mengatasi perkara lain yang lebih penting, atau jika ia diperoleh dengan cara yang salah.\n\nRUJUKAN: Pendidikan pengguna dan kewangan menekankan kepentingan membuat pilihan pembelian yang bijak berdasarkan bajet, kualiti, dan keperluan, bukan semata-mata jenama atau status. Konsep minimalisme juga semakin mendapat perhatian sebagai alternatif kepada budaya konsumerisme berlebihan.\n\nIMPLIKASI: Tekanan ini boleh menyebabkan pelajar merasa rendah diri, cemburu, atau terasing jika tidak mampu memiliki barangan tertentu. Ia juga boleh mendorong kepada pembaziran, hutang, atau konflik dengan ibu bapa mengenai wang.\n\nKESIMPULAN: Kesimpulannya, kita perlu memupuk sikap kesederhanaan dan penghargaan terhadap nilai bukan material. Ibu bapa boleh menjadi contoh dengan tidak terlalu menunjuk-nunjuk kemewahan. Sekolah boleh mengadakan perbincangan mengenai pengaruh iklan dan media. Menggalakkan pelajar untuk mencari kepuasan daripada pencapaian, perhubungan, atau sumbangan kepada masyarakat adalah lebih bermakna.",
            perkataan_sukar: [
                { perkataan: "Luaran", maksud: "Berkaitan dengan faktor di luar diri." },
                { perkataan: "Minimalisme", maksud: "Gaya hidup yang menekankan kesederhanaan dan pengurangan pemilikan harta benda." },
                { perkataan: "Konsumerisme", maksud: "Budaya yang menggalakkan pembelian barangan dan perkhidmatan secara berlebihan." },
                { perkataan: "Bermakna", maksud: "Mempunyai nilai atau kepentingan yang mendalam." }
            ]
        }
    }
});
